# Generated by Django 6.0.2 on 2026-02-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
