# Generated by Django 6.0.2 on 2026-02-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_application_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('fulltime', 'Full Time'), ('micro', 'Local / Micro Job')], default='fulltime', max_length=20),
        ),
    ]
