# Generated by Django 6.0.2 on 2026-02-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma separated skills (e.g. Python, Django, SQL)'),
        ),
    ]
